apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-sharded-cluster-configmap
data:
  database-host: >
    mongodb-sharded-cluster-statefulset-0.mongodb-sharded-cluster-service,
    mongodb-sharded-cluster-statefulset-1.mongodb-sharded-cluster-service
