version: '3.7'

services:
  registry:
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
  pypiserver:
    image: pypiserver/pypiserver:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - registry-data:/data
volumes:
  registry-data:
