apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sharded-cluster-statefulset
  labels:
    app: mongodb-sharded-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-sharded-cluster
  serviceName: mongodb-sharded-cluster-service
  template:
    metadata:
      labels:
        app: mongodb-sharded-cluster
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-sharded-cluster-pv-claim
            mountPath: /data/db
          - name: mongodb-keyfile-volume
            mountPath: /etc/mongodb-keyfile-volume
            readOnly: true
          - name: mongodb-mongod-conf-volume
            mountPath: /etc/mongod.conf
            subPath: mongod.conf
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-sharded-cluster-secret
                key: user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-sharded-cluster-secret
                key: password
          - name: SERVICE_FULL_HOST_NAME
            value: mongodb-sharded-cluster-service.default.svc.cluster.local
          - name: SERVICE_PORT
            value: "27017"
          - name: SERVICE_REPLICAS
            value: "2"
      volumes:
        - name: mongodb-keyfile-volume
          secret:
            secretName: mongodb-sharded-cluster-keyfile-secret
            items:
              - key: keyfile
                path: keyfile
                mode: 0600
        - name: mongodb-mongod-conf-volume
          configMap:
            name: mongodb-sharded-cluster-configmap
            items:
              - key: mongod.conf
                path: mongod.conf
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mongodb-sharded-cluster-pv-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
