apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-sharded-cluster-deployment
  labels:
    app: mongo-express-sharded-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-sharded-cluster
  template:
    metadata:
      labels:
        app: mongo-express-sharded-cluster
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-sharded-cluster-secret
                key: user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-sharded-cluster-secret
                key: password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-sharded-cluster-configmap
                key: database-host
