apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-single-deployment
  labels:
    app: mongo-express-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-single
  template:
    metadata:
      labels:
        app: mongo-express-single
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-single-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-single-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-single-configmap
                key: database-url
