import os

MONGODB_SINGLE_HOST = os.getenv("MONGODB_SINGLE_HOST")
MONGODB_SINGLE_PORT = int(os.getenv("MONGODB_SINGLE_PORT", 27017))
MONGODB_SINGLE_USER = os.getenv("MONGODB_SINGLE_USER")
MONGODB_SINGLE_PASSWORD = os.getenv("MONGODB_SINGLE_PASSWORD")

MONGODB_EXAMPLE_HOST = os.getenv("MONGODB_EXAMPLE_HOST")
MONGODB_EXAMPLE_PORT = int(os.getenv("MONGODB_EXAMPLE_PORT", 27017))
MONGODB_EXAMPLE_USER = os.getenv("MONGODB_EXAMPLE_USER")
MONGODB_EXAMPLE_PASSWORD = os.getenv("MONGODB_EXAMPLE_PASSWORD")
